name: Deploy to Heroku

on:
  workflow_dispatch:
    branches: '**'
  push:
    branches: [master]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v2
      - name: 'Deploy to Heroku'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: mmnc-task
          heroku_email: webovydesigner@gmail.com
